version: '{build}'
skip_tags: true
image: Visual Studio 2017
build_script:
- ps: ./Build.ps1 -majorMinor "5.1" -patch "$env:APPVEYOR_BUILD_VERSION" -customLogger "C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: SerilogWeb.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: A2krWFZ8w50sR0SapPbtCf/cUZ9fJInSwRJkyzab4tFO6KFCGX54a0NOxQinw9bL
  skip_symbols: true
  on:
    branch: master
